### ISSUE TITLE
Couldn't fetch compilation data; the format has probably changed. 

### ISSUE THREAD

**Issue by tertle** [needle-tools/compilation-visualizer#11]
1.8.3
Unity 2022.2.1f1

> System.IO.IOException: Sharing violation on path I:\Documents\Demos\Entities\Library\Bee\fullprofile.json
>   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0019e] in <8f06425e63004caf99a79845675f751e>:0 
>   at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <8f06425e63004caf99a79845675f751e>:0 
>   at (wrapper remoting-invoke-with-check) System.IO.FileStream..ctor(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions)
>   at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks, System.Int32 bufferSize) [0x00055] in <8f06425e63004caf99a79845675f751e>:0 
>   at System.IO.StreamReader..ctor (System.String path, System.Text.Encoding encoding, System.Boolean detectEncodingFromByteOrderMarks) [0x00000] in <8f06425e63004caf99a79845675f751e>:0 
>   at (wrapper remoting-invoke-with-check) System.IO.StreamReader..ctor(string,System.Text.Encoding,bool)
>   at System.IO.File.InternalReadAllText (System.String path, System.Text.Encoding encoding) [0x00000] in <8f06425e63004caf99a79845675f751e>:0 
>   at System.IO.File.ReadAllText (System.String path) [0x0002c] in <8f06425e63004caf99a79845675f751e>:0 
>   at Needle.CompilationVisualizer.CompilationData.ConvertBeeDataToCompilationData () [0x00021] in I:\Documents\Demos\Entities\Library\PackageCache\com.needle.compilation-visualizer@1.8.3\Editor\CompilationTrace.cs:99

**Comment by astro75** [comment]
1.8.3 works fine on Unity 2022.2.15

**Comment by hybridherbst** [comment]
Added an extra check in 1.8.4 that explicitly catches this exception in https://github.com/needle-tools/compilation-visualizer/issues/12.

It seems to be a race condition between Unity writing the data outside of their expected callbacks and Compilation Visualizer reading it.
