### ISSUE TITLE
Logging Toggle not respected

### ISSUE THREAD

**Issue by marwie** [needle-tools/compilation-visualizer#2]
STRP:

1) Open Window
2) Note "Logging Toggle" being off
3) Click on timeline elements in window
4) Note logs in console

![image](https://user-images.githubusercontent.com/5083203/94149037-acafff00-fe77-11ea-84bb-ead6e9a07ba3.png)

**Comment by hybridherbst** [comment]
Fixed in release 1.2.0, available now
