### ISSUE TITLE
Unity 2018.4.28f1 NullReferenceException on recompilation

### ISSUE THREAD

**Issue by rfadeev** [needle-tools/compilation-visualizer#3]
Hi,

Got following exceptions when clicking "Recompile" button from the compilation timeline window:
```
NullReferenceException: Object reference not set to an instance of an object
Needle.CompilationVisualizer.CompilationAnalysis.OnAssemblyCompilationStarted (System.String assembly) (at Packages/com.needle.compilation-visualizer@d99008755b85376fd5dec3a914d7fa544eded78d/Editor/CompilationAnalysis.cs:86)
UnityEditor.Compilation.CompilationPipeline.<SubscribeToEvents>m__0 (System.String assemblyPath) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CompilationPipeline.cs:117)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:346)
```
and
```
NullReferenceException: Object reference not set to an instance of an object
Needle.CompilationVisualizer.CompilationAnalysis.OnAssemblyCompilationFinished (System.String assembly, UnityEditor.Compilation.CompilerMessage[] arg2) (at Packages/com.needle.compilation-visualizer@d99008755b85376fd5dec3a914d7fa544eded78d/Editor/CompilationAnalysis.cs:110)
UnityEditor.Compilation.CompilationPipeline.<SubscribeToEvents>m__1 (System.String assemblyPath, UnityEditor.Compilation.CompilerMessage[] messages) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/CompilationPipeline.cs:130)
UnityEditor.Scripting.ScriptCompilation.EditorCompilationInterface:TickCompilationPipeline(EditorScriptCompilationOptions, BuildTargetGroup, BuildTarget) (at C:/buildslave/unity/build/Editor/Mono/Scripting/ScriptCompilation/EditorCompilationInterface.cs:346)
```
Exceptions seem to trigger for every assembly in the project. After a bit of investigation it turned out that following json is stored in EditorPrefs for `"Needle.CompilationVisualizer.CompilationData"` key:
```json
{
    "iterations": []
}
```

Tried clearing EditorPrefs for that key and restarting Unity and it did not help.

I wonder, is it a valid state of compilation data json to have empty iterations array? If yes, then it feels like that for the first assembly compilation started event need to change following [check](https://github.com/needle-tools/compilation-visualizer/blob/d99008755b85376fd5dec3a914d7fa544eded78d/Editor/CompilationAnalysis.cs#L86) to
```csharp
if (data == null || data.compilationFinished != DateTime.MinValue)
```

**Comment by hybridherbst** [comment]
Thanks for reporting here!

Does this only happen for that specific project or for all projects? I'll look into the iterations data state; 
I'll assume you're using the latest version available in PackMan?

**Comment by rfadeev** [comment]
This happened in the first project I added the package to. Tested now with the second project, the issue did not reproduce. Explanation as follows: after I applied the fix I mentioned (`data == null` check), compilation timeline editor window started to work. This results in non-empty iterations added to `"Needle.CompilationVisualizer.CompilationData"` EditorPrefs key. Since EditorPrefs are shared between Unity installations, second project uses that value and no exceptions are thrown.

To reproduce exception in the second project, I removed `""Needle.CompilationVisualizer.CompilationData"`  key and corresponding value from EditorPrefs. After that triggering recompilation via "Recompile" toolbar button results in the exception as in the first project.

Both projects are dummy stub projects created from templates with single script added.

Not sure about what PacMan is, I added package directly like:
```json
{
  "dependencies": {
    "com.needle.compilation-visualizer": "https://github.com/needle-tools/compilation-visualizer.git#release/1.2.1"
  }
}
```
To apply fix I had to move the package to become local though.

**Comment by hybridherbst** [comment]
Thanks for the detailled investigation! This issue specifically affected 2018.4.
I added the null check you suggested; a new version 1.2.2 is available now.

Note that you can use the OpenUPM version of this package as well, and then you can directly update via Package Manager Window.

**Comment by rfadeev** [comment]
Great, thanks for the fast fix of the issue! 👍
