### ISSUE TITLE
Total time for PlayMode compilation keeps running in the background

### ISSUE THREAD

**Issue by KalinAngelo** [needle-tools/compilation-visualizer#6]
I am working on an Android only project. Currently do not have a non Android project on my machine. On play compilation visualizer is triggered and appears to record the compilation and reload time accurately, however, the total time seems to be an arbitrary number, usually around 100 seconds. Every now and again it shoots up to 1000 seconds. I've repeated on play 30 times, restarted Unity after the 15th time before continuing.

![image](https://user-images.githubusercontent.com/48099517/139688051-f7a312da-031e-4e1d-b3a3-bbfb6fd5d358.png)

![image](https://user-images.githubusercontent.com/48099517/139688146-0cf0ccb9-e1a9-4503-bd95-78bb2e9a719e.png)

**Comment by hybridherbst** [comment]
Interesting, thanks for the report @KalinAngelo.

Would this be accurate steps to repro if I get you right?
- open CompViz
- enter PlayMode
- expected: shows compilation and stops when domain reload is over
- actual: keeps running either for a random time or forever
?

**Comment by KalinAngelo** [comment]
Unity Version 2020.3.18f1
Apologies for not including any steps, completely forgot.

1. Open CompViz
2. Enter PlayMode
3. Exit PlayMode
4. Wait 20 seconds
5. Enter PlayMode
6. Exit PlayMode
* Expected Behaviour: **After first exit of PlayMode:** CompViz stops and shows correct total, compilation, and reload times when domain reload has finished, e.g. total 5, compilation 1.5, reload 3.5. **After second exit of PlayMode:** CompViz stops and shows correct times, e.g. total 6, compilation 2.5, reload 3.5.
* Actual: **After first exit of PlayMode:** CompViz stops and shows correct total, compilation, and reload times, e.g. total 5, compilation 1.5, reload 3.5. **After second exit of PlayMode:** Total time is equal to current reload + current compilation + time since the first domain reload, e.g. total 30, compilation 1.5, reload 3.5.
* 2 Unity restarts ago the total time was continuously stuck at 98.80 seconds, now it just counts up and I cannot reproduce the 98.80 seconds.

Edit: Now climbs to 1200-ish seconds but does not exceed that. Persists after Unity restart.

**Comment by hybridherbst** [comment]
Hey @KalinAngelo, could you check if this issue is fixed in 1.7.0 for you?

The reload times were incorrectly updating when entering playmode - they are supposed to update only after an actual compilation, otherwise the timings don't make much sense in relation to compilation. So now, when you enter/exit play modes basically nothing should change in the Compilation Visualizer window.
