### ISSUE TITLE
Add the ability to zoom

### ISSUE THREAD

**Issue by KuraiAndras** [needle-tools/compilation-visualizer#7]
It would be nice if we could have the ability to zoom into the timeline. Right now, we get this result and it is rather hard to read
![image](https://user-images.githubusercontent.com/19240945/151344171-a9150cd3-f7db-439e-8c13-80cecbab8c64.png)

**Comment by hybridherbst** [comment]
The ~200 seconds until anything happens look wrong, does this look the same when you press "Recompile" here?

**Comment by KuraiAndras** [comment]
Yes it does. I am trying to pinpoint why our compilation times are so long (~30-40 seconds when changing something trivial in a C# file)

**Comment by hybridherbst** [comment]
Could you let me know a few more things please:
- Unity version
- Comp Viz version
- the manifest.json (redacted if need be)

**Comment by KuraiAndras** [comment]
- Unity 2021.2.8
- CompilationVisualizer 1.7.0

<details>
  <summary>manifest</summary>
  
```json
{
  "dependencies": {
    "com.autsoft.unityresourcegenerator": "1.0.1",
    "com.cysharp.unitask": "2.2.5",
    "com.demigiant.dotween": "1.2.632",
    "com.injecter.hosting.unity": "6.1.2",
    "com.injecter.unity": "6.1.2",
    "com.mapbox.sdk": "file:../../Mapbox",
    "com.serilog.sinks.unity3d": "2.0.1",
    "com.unity.2d.sprite": "1.0.0",
    "com.unity.feature.development": "1.0.1",
    "com.unity.ide.rider": "3.0.10",
    "com.unity.ide.visualstudio": "2.0.14",
    "com.unity.ide.vscode": "1.2.4",
    "com.unity.test-framework": "1.1.30",
    "com.unity.textmeshpro": "3.0.6",
    "com.unity.timeline": "1.6.3",
    "com.unity.toolchain.win-x86_64-linux-x86_64": "1.0.0",
    "com.unity.ugui": "1.0.0",
    "org.nuget.injecter": "6.1.2",
    "org.nuget.microsoft.bcl.asyncinterfaces": "5.0.0",
    "org.nuget.microsoft.extensions.dependencymodel": "6.0.0",
    "org.nuget.microsoft.extensions.hosting": "6.0.0",
    "org.nuget.microsoft.extensions.http": "6.0.0",
    "org.nuget.microsoft.toolkit.mvvm": "7.1.2",
    "org.nuget.microsoft.unity.analyzers": "1.12.0",
    "org.nuget.morelinq": "3.3.2",
    "org.nuget.roslynator.analyzers": "4.0.0",
    "org.nuget.serilog": "2.10.0",
    "org.nuget.serilog.extensions.hosting": "4.2.0",
    "org.nuget.sonaranalyzer.csharp": "8.34.0-42011",
    "org.nuget.system.collections.immutable": "6.0.0",
    "com.unity.modules.ai": "1.0.0",
    "com.unity.modules.androidjni": "1.0.0",
    "com.unity.modules.animation": "1.0.0",
    "com.unity.modules.assetbundle": "1.0.0",
    "com.unity.modules.audio": "1.0.0",
    "com.unity.modules.cloth": "1.0.0",
    "com.unity.modules.director": "1.0.0",
    "com.unity.modules.imageconversion": "1.0.0",
    "com.unity.modules.imgui": "1.0.0",
    "com.unity.modules.jsonserialize": "1.0.0",
    "com.unity.modules.particlesystem": "1.0.0",
    "com.unity.modules.physics": "1.0.0",
    "com.unity.modules.physics2d": "1.0.0",
    "com.unity.modules.screencapture": "1.0.0",
    "com.unity.modules.terrain": "1.0.0",
    "com.unity.modules.terrainphysics": "1.0.0",
    "com.unity.modules.tilemap": "1.0.0",
    "com.unity.modules.ui": "1.0.0",
    "com.unity.modules.uielements": "1.0.0",
    "com.unity.modules.umbra": "1.0.0",
    "com.unity.modules.unityanalytics": "1.0.0",
    "com.unity.modules.unitywebrequest": "1.0.0",
    "com.unity.modules.unitywebrequestassetbundle": "1.0.0",
    "com.unity.modules.unitywebrequestaudio": "1.0.0",
    "com.unity.modules.unitywebrequesttexture": "1.0.0",
    "com.unity.modules.unitywebrequestwww": "1.0.0",
    "com.unity.modules.vehicles": "1.0.0",
    "com.unity.modules.video": "1.0.0",
    "com.unity.modules.vr": "1.0.0",
    "com.unity.modules.wind": "1.0.0",
    "com.unity.modules.xr": "1.0.0",
    "com.needle.compilation-visualizer": "1.7.0"
  },
  "scopedRegistries": [
    {
      "name": "Unity NuGet",
      "url": "https://unitynuget-registry.azurewebsites.net",
      "scopes": [
        "org.nuget"
      ]
    },
    {
      "name": "package.openupm.com",
      "url": "https://package.openupm.com",
      "scopes": [
        "com.autsoft.unityresourcegenerator",
        "com.cysharp.unitask",
        "com.demigiant.dotween",
        "com.injecter.hosting.unity",
        "com.injecter.unity",
        "com.needle.compilation-visualizer",
        "com.openupm",
        "com.serilog.sinks.unity3d"
      ]
    }
  ]
}
```
</details>

csc.rsp:
```
-nullable:enable
-nowarn:S3168
-nowarn:S3358
-nowarn:S1135
```

I am suspecting that the compilations are increased because of the roslyn anaylzers. Since they are resolved using xoofx's nuget server they are run against every asmdef (not just the ones present under the Assets folder). You can leave out the mapbox reference, we forked that and added assmebly definitions where they were applicable, otherwise it is identical to the reference version.

**Comment by KuraiAndras** [comment]
@hybridherbst I have found the culprit. Disabling roslyn analyzers in unity reduces the compilation time significantly. When using visual studio and adding the analyzers through xoofx's unity nuget server the analyzers are picked up by visual studio so they are still useful, but the warnings are not displayed inside the unity console. The problem is that source generators will not work. Visual Studio will still see them, and generate the additional files, but unity will not pick them up in the compilation process.

**Comment by hybridherbst** [comment]
That's interesting to know @KuraiAndras, thanks for pointing that out. So they add a lot of time _before_ compilation actually it seems, judging from the timeline? My understanding was that they run afterwards... (don't have much experience using them in Unity yet)

**Comment by KuraiAndras** [comment]
Analyzers disabled:
![image](https://user-images.githubusercontent.com/19240945/156731544-f3b4ea41-5db6-4f9f-82e6-736883ec4bb2.png)
Analyzers enabled:
![image](https://user-images.githubusercontent.com/19240945/156732775-7d3895cc-9c26-4712-826f-ac2cb5c26116.png)
both of these are after a couple of recompiles, just to make sure (and they consistently run at these speeds)
It seems that both the time before the actual compilation and the compilation times themselves increase when analyzers are disabled.

Analyzers in use:
- Roslynator.Analyzers
- SonarAnalyzer
- Microsoft.Unity.Analyzer
 
Source Generator:
- Microsoft.Toolkit.Mvvm

Unity:
- 2021.2.14
- .NET Standard profile

**Comment by hybridherbst** [comment]
Added the ability to zoom in 1.8.0, available now :)
Let me know what you think / if something isn't working for you!
