### ISSUE TITLE
[Question] Is this a replacement for the abandoned Iteration Profiler?

### ISSUE THREAD

**Issue by StepanMynarik** [needle-tools/compilation-visualizer#8]
Because that would be sweet 😁

**Comment by hybridherbst** [comment]
It's a different usecase right now!

EIP is designed to surface slow _domain reload_ times, so basically whatever happens _after_ compilation;
Compilation Visualizer is designed to show _compilation times_, so which assemblies take how long, are your depenendcies properly set up, are only the things you expect to be recompiled when you change a file actually recompiled, ...
